spring:
  application:
    name: resume-coach-api

  # 데이터베이스 설정 (H2 인메모리 DB)
  datasource:
    url: jdbc:h2:mem:${DB_NAME:resume}
    driver-class-name: org.h2.Driver
    username: ${DB_USERNAME:admin}
    password: ${DB_PASSWORD:1234}

  mvc:
    async:
      request-timeout: 910000

  # H2 콘솔 설정
  h2:
    console:
      enabled: true
      path: /h2-console

  # JPA 설정
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: false
        use_sql_comments: false
    defer-datasource-initialization: false

  sql:
    init:
      mode: never

# 서버 설정
server:
  compression:
    enabled: true
    mime-types: application/json,text/html,text/plain
  port: ${PORT:9070}
  servlet:
    context-path: /


ollama:
  api:
    base-url:  ${OLLAMA_BASE_URL:http://ollama:11434}
    end-point: /api/chat
    timeout:
      connect: 30
      read: 900
  model: ${OLLAMA_MODEL:benedict/linkbricks-llama3.1-korean:8b}

# AI 서비스 공급자
ai:
  provider: ollama

# 로깅 설정
logging:
  level:
    com.careercoach: INFO
    org.springframework.web: INFO
    org.hibernate.SQL: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"

# 애플리케이션 정보
info:
  app:
    name: Resume Coach API
    description: AI-powered resume coaching chatbot API
    version: 1.0.0
    ai-provider: Ollama
    model: ${ollama.model}
    developer: asdf with ClaudeSonnet4

# Swagger/OpenAPI 설정
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /
    operationsSorter: method
    tagsSorter: alpha
    try-it-out-enabled: true
    filter: true
    display-request-duration: true
  show-actuator: false
  default-consumes-media-type: application/json
  default-produces-media-type: application/json

# Swagger 서버 URL 설정
swagger:
  server:
    url: ${SWAGGER_SERVER_URL}:${server.port}